# lazygit config
# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  showIcons: true
  nerdFontsVersion: "3"

git:
  mainBranches:
    - "trunk"
  pagers:
    - colorArg: "always"
      pager: "delta --dark --paging=never"
