[general]
import = [
  "~/.config/alacritty/dank-theme.toml"
]

[font]
size = 14

[font.normal]
family = "CommitMono Nerd Font"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
